name: Webhooks Api Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
       - "Webhooks.API/**"

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build container image
      run: docker build -f Webhooks.API/Dockerfile -t webhooksapi:$(echo $GITHUB_SHA | head -c7) .

    - name: Tag Image  
      run: docker tag webhooksapi:$(echo $GITHUB_SHA | head -c7) nguyenvantu/webhooksapi:$(echo $GITHUB_SHA | head -c7)

    - name: Push image to Docker Hub
      run: docker push nguyenvantu/webhooksapi:$(echo $GITHUB_SHA | head -c7)

    - name: Update deployment file
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        sed -i 's|nguyenvantu/webhooksapi:.*|nguyenvantu/webhooksapi:'${TAG}'|' MultiAppServer.AppHost/aspirate-output/webhooksapi/deployment.yaml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -k MultiAppServer.AppHost/aspirate-output/webhooksapi/.

    # - name: Verify deployment
    #   run: kubectl rollout status deployment/webapp
